Amp subsystem
Comets3357/2024Offseason_RoboChargersClone pull request #11
Opened 2024-10-10 23:59 UTC by AgrawalDevansh09

2024-10-11 13:13 UTC, YeetDot requested changes
Change those things

2024-10-11 13:13 UTC, YeetDot commented on src/main/cpp/RobotContainer.cpp
> +  DriverController.X().OnTrue(AmpEject(&Amp));
These should not be in the Constructor, but rather in ConfigureBindings.

2024-10-11 13:13 UTC, YeetDot commented on src/main/include/RobotContainer.h
> +#include <frc/XboxController.h>
Are all these includes required?

2024-10-11 18:06 UTC, AgrawalDevansh09 commented
Implimented Changes

2024-10-14 13:13 UTC, YeetDot approved these changes
I think it's good now but <sub>Camden</sub> probably has something to say

2024-10-16 21:47 UTC, cpastyrn3357 requested changes

2024-10-16 21:47 UTC, cpastyrn3357 commented on src/main/cpp/Subsystems/AmpSubsystem.cpp
> +void AmpSubsystem::AmpExtend(double AmpExtendPower)
Probably remove amp extend. Not needed and could cause confusion

2024-10-16 21:47 UTC, cpastyrn3357 commented on src/main/include/Subsystems/AmpSubsystem.h
> +        void AmpExtend(double AmpExtendPower);
And remove amp extend here too.

2024-10-16 21:47 UTC, cpastyrn3357 commented on src/main/cpp/RobotContainer.cpp
> +
Nit picky, but try to remove changes in whitespace where possible

2024-10-16 21:47 UTC, cpastyrn3357 commented on src/main/include/Subsystems/AmpSubsystem.h
> +        //void Periodic() override;
Remove periodic, since it is not being used.

2024-10-16 21:47 UTC, cpastyrn3357 commented on src/main/include/Commands/AmpCommands.h
> +#include "frc2/command/Commands.h"
Move this include to the cpp file and use < > for WPILib includes

2024-10-16 23:54 UTC, cpastyrn3357 approved these changes

2024-10-17 00:08 UTC, merged

2024-10-17 00:09 UTC, AgrawalDevansh09 commented
Merged into Amp